/**
 MIT License

 Copyright (c) 2020 Felix Vogel

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */
package de.felix.webserver;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

/**
 * Keeps some of the most used mime types, can be extended for any file
 *
 * @author Felix Vogel
 */
public final class MimeType {

    private static final Map<String, MimeType> MIME_TYPES = new HashMap<>(700);

    static {
        // @formatter:off
        MIME_TYPES.put(".x3d",         new MimeType("application/vnd.hzn-3d-crossword"));
        MIME_TYPES.put(".3gp",         new MimeType("video/3gpp"));
        MIME_TYPES.put(".3g2",         new MimeType("video/3gpp2"));
        MIME_TYPES.put(".mseq",        new MimeType("application/vnd.mseq"));
        MIME_TYPES.put(".pwn",         new MimeType("application/vnd.3m.post-it-notes"));
        MIME_TYPES.put(".plb",         new MimeType("application/vnd.3gpp.pic-bw-large"));
        MIME_TYPES.put(".psb",         new MimeType("application/vnd.3gpp.pic-bw-small"));
        MIME_TYPES.put(".pvb",         new MimeType("application/vnd.3gpp.pic-bw-var"));
        MIME_TYPES.put(".tcap",        new MimeType("application/vnd.3gpp2.tcap"));
        MIME_TYPES.put(".7z",          new MimeType("application/x-7z-compressed"));
        MIME_TYPES.put(".abw",         new MimeType("application/x-abiword"));
        MIME_TYPES.put(".ace",         new MimeType("application/x-ace-compressed"));
        MIME_TYPES.put(".acc",         new MimeType("application/vnd.americandynamics.acc"));
        MIME_TYPES.put(".acu",         new MimeType("application/vnd.acucobol"));
        MIME_TYPES.put(".atc",         new MimeType("application/vnd.acucorp"));
        MIME_TYPES.put(".adp",         new MimeType("audio/adpcm"));
        MIME_TYPES.put(".aab",         new MimeType("application/x-authorware-bin"));
        MIME_TYPES.put(".aam",         new MimeType("application/x-authorware-map"));
        MIME_TYPES.put(".aas",         new MimeType("application/x-authorware-seg"));
        MIME_TYPES.put(".air",         new MimeType("application/vnd.adobe.air-application-installer-package+zip"));
        MIME_TYPES.put(".swf",         new MimeType("application/x-shockwave-flash"));
        MIME_TYPES.put(".fxp",         new MimeType("application/vnd.adobe.fxp"));
        MIME_TYPES.put(".pdf",         new MimeType("application/pdf"));
        MIME_TYPES.put(".ppd",         new MimeType("application/vnd.cups-ppd"));
        MIME_TYPES.put(".dir",         new MimeType("application/x-director"));
        MIME_TYPES.put(".xdp",         new MimeType("application/vnd.adobe.xdp+xml"));
        MIME_TYPES.put(".xfdf",        new MimeType("application/vnd.adobe.xfdf"));
        MIME_TYPES.put(".aac",         new MimeType("audio/x-aac"));
        MIME_TYPES.put(".ahead",       new MimeType("application/vnd.ahead.space"));
        MIME_TYPES.put(".azf",         new MimeType("application/vnd.airzip.filesecure.azf"));
        MIME_TYPES.put(".azs",         new MimeType("application/vnd.airzip.filesecure.azs"));
        MIME_TYPES.put(".azw",         new MimeType("application/vnd.amazon.ebook"));
        MIME_TYPES.put(".ami",         new MimeType("application/vnd.amiga.ami"));
        MIME_TYPES.put("N/A",          new MimeType("application/andrew-inset"));
        MIME_TYPES.put(".apk",         new MimeType("application/vnd.android.package-archive"));
        MIME_TYPES.put(".cii",         new MimeType("application/vnd.anser-web-certificate-issue-initiation"));
        MIME_TYPES.put(".fti",         new MimeType("application/vnd.anser-web-funds-transfer-initiation"));
        MIME_TYPES.put(".atx",         new MimeType("application/vnd.antix.game-component"));
        MIME_TYPES.put(".dmg",         new MimeType("application/x-apple-diskimage"));
        MIME_TYPES.put(".mpkg",        new MimeType("application/vnd.apple.installer+xml"));
        MIME_TYPES.put(".aw",          new MimeType("application/applixware"));
        MIME_TYPES.put(".les",         new MimeType("application/vnd.hhe.lesson-player"));
        MIME_TYPES.put(".swi",         new MimeType("application/vnd.aristanetworks.swi"));
        MIME_TYPES.put(".s",           new MimeType("text/x-asm"));
        MIME_TYPES.put(".atomcat",     new MimeType("application/atomcat+xml"));
        MIME_TYPES.put(".atomsvc",     new MimeType("application/atomsvc+xml"));
        MIME_TYPES.put(".atom, .xml",  new MimeType("application/atom+xml"));
        MIME_TYPES.put(".ac",          new MimeType("application/pkix-attr-cert"));
        MIME_TYPES.put(".aif",         new MimeType("audio/x-aiff"));
        MIME_TYPES.put(".avi",         new MimeType("video/x-msvideo"));
        MIME_TYPES.put(".aep",         new MimeType("application/vnd.audiograph"));
        MIME_TYPES.put(".dxf",         new MimeType("image/vnd.dxf"));
        MIME_TYPES.put(".dwf",         new MimeType("model/vnd.dwf"));
        MIME_TYPES.put(".par",         new MimeType("text/plain-bas"));
        MIME_TYPES.put(".bcpio",       new MimeType("application/x-bcpio"));
        MIME_TYPES.put(".bin",         new MimeType("application/octet-stream"));
        MIME_TYPES.put(".bmp",         new MimeType("image/bmp"));
        MIME_TYPES.put(".torrent",     new MimeType("application/x-bittorrent"));
        MIME_TYPES.put(".cod",         new MimeType("application/vnd.rim.cod"));
        MIME_TYPES.put(".mpm",         new MimeType("application/vnd.blueice.multipass"));
        MIME_TYPES.put(".bmi",         new MimeType("application/vnd.bmi"));
        MIME_TYPES.put(".sh",          new MimeType("application/x-sh"));
        MIME_TYPES.put(".btif",        new MimeType("image/prs.btif"));
        MIME_TYPES.put(".rep",         new MimeType("application/vnd.businessobjects"));
        MIME_TYPES.put(".bz",          new MimeType("application/x-bzip"));
        MIME_TYPES.put(".bz2",         new MimeType("application/x-bzip2"));
        MIME_TYPES.put(".csh",         new MimeType("application/x-csh"));
        MIME_TYPES.put(".c",           new MimeType("text/x-c"));
        MIME_TYPES.put(".cdxml",       new MimeType("application/vnd.chemdraw+xml"));
        MIME_TYPES.put(".css",         new MimeType("text/css"));
        MIME_TYPES.put(".cdx",         new MimeType("chemical/x-cdx"));
        MIME_TYPES.put(".cml",         new MimeType("chemical/x-cml"));
        MIME_TYPES.put(".csml",        new MimeType("chemical/x-csml"));
        MIME_TYPES.put(".cdbcmsg",     new MimeType("application/vnd.contact.cmsg"));
        MIME_TYPES.put(".cla",         new MimeType("application/vnd.claymore"));
        MIME_TYPES.put(".c4g",         new MimeType("application/vnd.clonk.c4group"));
        MIME_TYPES.put(".sub",         new MimeType("image/vnd.dvb.subtitle"));
        MIME_TYPES.put(".cdmia",       new MimeType("application/cdmi-capability"));
        MIME_TYPES.put(".cdmic",       new MimeType("application/cdmi-container"));
        MIME_TYPES.put(".cdmid",       new MimeType("application/cdmi-domain"));
        MIME_TYPES.put(".cdmio",       new MimeType("application/cdmi-object"));
        MIME_TYPES.put(".cdmiq",       new MimeType("application/cdmi-queue"));
        MIME_TYPES.put(".c11amc",      new MimeType("application/vnd.cluetrust.cartomobile-config"));
        MIME_TYPES.put(".c11amz",      new MimeType("application/vnd.cluetrust.cartomobile-config-pkg"));
        MIME_TYPES.put(".ras",         new MimeType("image/x-cmu-raster"));
        MIME_TYPES.put(".dae",         new MimeType("model/vnd.collada+xml"));
        MIME_TYPES.put(".csv",         new MimeType("text/csv"));
        MIME_TYPES.put(".cpt",         new MimeType("application/mac-compactpro"));
        MIME_TYPES.put(".wmlc",        new MimeType("application/vnd.wap.wmlc"));
        MIME_TYPES.put(".cgm",         new MimeType("image/cgm"));
        MIME_TYPES.put(".ice",         new MimeType("x-conference/x-cooltalk"));
        MIME_TYPES.put(".cmx",         new MimeType("image/x-cmx"));
        MIME_TYPES.put(".xar",         new MimeType("application/vnd.xara"));
        MIME_TYPES.put(".cmc",         new MimeType("application/vnd.cosmocaller"));
        MIME_TYPES.put(".cpio",        new MimeType("application/x-cpio"));
        MIME_TYPES.put(".clkx",        new MimeType("application/vnd.crick.clicker"));
        MIME_TYPES.put(".clkk",        new MimeType("application/vnd.crick.clicker.keyboard"));
        MIME_TYPES.put(".clkp",        new MimeType("application/vnd.crick.clicker.palette"));
        MIME_TYPES.put(".clkt",        new MimeType("application/vnd.crick.clicker.template"));
        MIME_TYPES.put(".clkw",        new MimeType("application/vnd.crick.clicker.wordbank"));
        MIME_TYPES.put(".wbs",         new MimeType("application/vnd.criticaltools.wbs+xml"));
        MIME_TYPES.put(".cryptonote",  new MimeType("application/vnd.rig.cryptonote"));
        MIME_TYPES.put(".cif",         new MimeType("chemical/x-cif"));
        MIME_TYPES.put(".cmdf",        new MimeType("chemical/x-cmdf"));
        MIME_TYPES.put(".cu",          new MimeType("application/cu-seeme"));
        MIME_TYPES.put(".cww",         new MimeType("application/prs.cww"));
        MIME_TYPES.put(".curl",        new MimeType("text/vnd.curl"));
        MIME_TYPES.put(".dcurl",       new MimeType("text/vnd.curl.dcurl"));
        MIME_TYPES.put(".mcurl",       new MimeType("text/vnd.curl.mcurl"));
        MIME_TYPES.put(".scurl",       new MimeType("text/vnd.curl.scurl"));
        MIME_TYPES.put(".car",         new MimeType("application/vnd.curl.car"));
        MIME_TYPES.put(".pcurl",       new MimeType("application/vnd.curl.pcurl"));
        MIME_TYPES.put(".cmp",         new MimeType("application/vnd.yellowriver-custom-menu"));
        MIME_TYPES.put(".dssc",        new MimeType("application/dssc+der"));
        MIME_TYPES.put(".xdssc",       new MimeType("application/dssc+xml"));
        MIME_TYPES.put(".deb",         new MimeType("application/x-debian-package"));
        MIME_TYPES.put(".uva",         new MimeType("audio/vnd.dece.audio"));
        MIME_TYPES.put(".uvi",         new MimeType("image/vnd.dece.graphic"));
        MIME_TYPES.put(".uvh",         new MimeType("video/vnd.dece.hd"));
        MIME_TYPES.put(".uvm",         new MimeType("video/vnd.dece.mobile"));
        MIME_TYPES.put(".uvu",         new MimeType("video/vnd.uvvu.mp4"));
        MIME_TYPES.put(".uvp",         new MimeType("video/vnd.dece.pd"));
        MIME_TYPES.put(".uvs",         new MimeType("video/vnd.dece.sd"));
        MIME_TYPES.put(".uvv",         new MimeType("video/vnd.dece.video"));
        MIME_TYPES.put(".dvi",         new MimeType("application/x-dvi"));
        MIME_TYPES.put(".seed",        new MimeType("application/vnd.fdsn.seed"));
        MIME_TYPES.put(".dtb",         new MimeType("application/x-dtbook+xml"));
        MIME_TYPES.put(".res",         new MimeType("application/x-dtbresource+xml"));
        MIME_TYPES.put(".ait",         new MimeType("application/vnd.dvb.ait"));
        MIME_TYPES.put(".svc",         new MimeType("application/vnd.dvb.service"));
        MIME_TYPES.put(".eol",         new MimeType("audio/vnd.digital-winds"));
        MIME_TYPES.put(".djvu",        new MimeType("image/vnd.djvu"));
        MIME_TYPES.put(".dtd",         new MimeType("application/xml-dtd"));
        MIME_TYPES.put(".mlp",         new MimeType("application/vnd.dolby.mlp"));
        MIME_TYPES.put(".wad",         new MimeType("application/x-doom"));
        MIME_TYPES.put(".dpg",         new MimeType("application/vnd.dpgraph"));
        MIME_TYPES.put(".dra",         new MimeType("audio/vnd.dra"));
        MIME_TYPES.put(".dfac",        new MimeType("application/vnd.dreamfactory"));
        MIME_TYPES.put(".dts",         new MimeType("audio/vnd.dts"));
        MIME_TYPES.put(".dtshd",       new MimeType("audio/vnd.dts.hd"));
        MIME_TYPES.put(".dwg",         new MimeType("image/vnd.dwg"));
        MIME_TYPES.put(".geo",         new MimeType("application/vnd.dynageo"));
        MIME_TYPES.put(".es",          new MimeType("application/ecmascript"));
        MIME_TYPES.put(".mag",         new MimeType("application/vnd.ecowin.chart"));
        MIME_TYPES.put(".mmr",         new MimeType("image/vnd.fujixerox.edmics-mmr"));
        MIME_TYPES.put(".rlc",         new MimeType("image/vnd.fujixerox.edmics-rlc"));
        MIME_TYPES.put(".exi",         new MimeType("application/exi"));
        MIME_TYPES.put(".mgz",         new MimeType("application/vnd.proteus.magazine"));
        MIME_TYPES.put(".epub",        new MimeType("application/epub+zip"));
        MIME_TYPES.put(".eml",         new MimeType("message/rfc822"));
        MIME_TYPES.put(".nml",         new MimeType("application/vnd.enliven"));
        MIME_TYPES.put(".xpr",         new MimeType("application/vnd.is-xpr"));
        MIME_TYPES.put(".xif",         new MimeType("image/vnd.xiff"));
        MIME_TYPES.put(".xfdl",        new MimeType("application/vnd.xfdl"));
        MIME_TYPES.put(".emma",        new MimeType("application/emma+xml"));
        MIME_TYPES.put(".ez2",         new MimeType("application/vnd.ezpix-album"));
        MIME_TYPES.put(".ez3",         new MimeType("application/vnd.ezpix-package"));
        MIME_TYPES.put(".fst",         new MimeType("image/vnd.fst"));
        MIME_TYPES.put(".fvt",         new MimeType("video/vnd.fvt"));
        MIME_TYPES.put(".fbs",         new MimeType("image/vnd.fastbidsheet"));
        MIME_TYPES.put(".fe_launch",   new MimeType("application/vnd.denovo.fcselayout-link"));
        MIME_TYPES.put(".f4v",         new MimeType("video/x-f4v"));
        MIME_TYPES.put(".flv",         new MimeType("video/x-flv"));
        MIME_TYPES.put(".fpx",         new MimeType("image/vnd.fpx"));
        MIME_TYPES.put(".npx",         new MimeType("image/vnd.net-fpx"));
        MIME_TYPES.put(".flx",         new MimeType("text/vnd.fmi.flexstor"));
        MIME_TYPES.put(".fli",         new MimeType("video/x-fli"));
        MIME_TYPES.put(".ftc",         new MimeType("application/vnd.fluxtime.clip"));
        MIME_TYPES.put(".fdf",         new MimeType("application/vnd.fdf"));
        MIME_TYPES.put(".f",           new MimeType("text/x-fortran"));
        MIME_TYPES.put(".mif",         new MimeType("application/vnd.mif"));
        MIME_TYPES.put(".fm",          new MimeType("application/vnd.framemaker"));
        MIME_TYPES.put(".fh",          new MimeType("image/x-freehand"));
        MIME_TYPES.put(".fsc",         new MimeType("application/vnd.fsc.weblaunch"));
        MIME_TYPES.put(".fnc",         new MimeType("application/vnd.frogans.fnc"));
        MIME_TYPES.put(".ltf",         new MimeType("application/vnd.frogans.ltf"));
        MIME_TYPES.put(".ddd",         new MimeType("application/vnd.fujixerox.ddd"));
        MIME_TYPES.put(".xdw",         new MimeType("application/vnd.fujixerox.docuworks"));
        MIME_TYPES.put(".xbd",         new MimeType("application/vnd.fujixerox.docuworks.binder"));
        MIME_TYPES.put(".oas",         new MimeType("application/vnd.fujitsu.oasys"));
        MIME_TYPES.put(".oa2",         new MimeType("application/vnd.fujitsu.oasys2"));
        MIME_TYPES.put(".oa3",         new MimeType("application/vnd.fujitsu.oasys3"));
        MIME_TYPES.put(".fg5",         new MimeType("application/vnd.fujitsu.oasysgp"));
        MIME_TYPES.put(".bh2",         new MimeType("application/vnd.fujitsu.oasysprs"));
        MIME_TYPES.put(".spl",         new MimeType("application/x-futuresplash"));
        MIME_TYPES.put(".fzs",         new MimeType("application/vnd.fuzzysheet"));
        MIME_TYPES.put(".g3",          new MimeType("image/g3fax"));
        MIME_TYPES.put(".gmx",         new MimeType("application/vnd.gmx"));
        MIME_TYPES.put(".gtw",         new MimeType("model/vnd.gtw"));
        MIME_TYPES.put(".txd",         new MimeType("application/vnd.genomatix.tuxedo"));
        MIME_TYPES.put(".ggb",         new MimeType("application/vnd.geogebra.file"));
        MIME_TYPES.put(".ggt",         new MimeType("application/vnd.geogebra.tool"));
        MIME_TYPES.put(".gdl",         new MimeType("model/vnd.gdl"));
        MIME_TYPES.put(".gex",         new MimeType("application/vnd.geometry-explorer"));
        MIME_TYPES.put(".gxt",         new MimeType("application/vnd.geonext"));
        MIME_TYPES.put(".g2w",         new MimeType("application/vnd.geoplan"));
        MIME_TYPES.put(".g3w",         new MimeType("application/vnd.geospace"));
        MIME_TYPES.put(".gsf",         new MimeType("application/x-font-ghostscript"));
        MIME_TYPES.put(".bdf",         new MimeType("application/x-font-bdf"));
        MIME_TYPES.put(".gtar",        new MimeType("application/x-gtar"));
        MIME_TYPES.put(".texinfo",     new MimeType("application/x-texinfo"));
        MIME_TYPES.put(".gnumeric",    new MimeType("application/x-gnumeric"));
        MIME_TYPES.put(".kml",         new MimeType("application/vnd.google-earth.kml+xml"));
        MIME_TYPES.put(".kmz",         new MimeType("application/vnd.google-earth.kmz"));
        MIME_TYPES.put(".gqf",         new MimeType("application/vnd.grafeq"));
        MIME_TYPES.put(".gif",         new MimeType("image/gif"));
        MIME_TYPES.put(".gv",          new MimeType("text/vnd.graphviz"));
        MIME_TYPES.put(".gac",         new MimeType("application/vnd.groove-account"));
        MIME_TYPES.put(".ghf",         new MimeType("application/vnd.groove-help"));
        MIME_TYPES.put(".gim",         new MimeType("application/vnd.groove-identity-message"));
        MIME_TYPES.put(".grv",         new MimeType("application/vnd.groove-injector"));
        MIME_TYPES.put(".gtm",         new MimeType("application/vnd.groove-tool-message"));
        MIME_TYPES.put(".tpl",         new MimeType("application/vnd.groove-tool-template"));
        MIME_TYPES.put(".vcg",         new MimeType("application/vnd.groove-vcard"));
        MIME_TYPES.put(".h261",        new MimeType("video/h261"));
        MIME_TYPES.put(".h263",        new MimeType("video/h263"));
        MIME_TYPES.put(".h264",        new MimeType("video/h264"));
        MIME_TYPES.put(".hpid",        new MimeType("application/vnd.hp-hpid"));
        MIME_TYPES.put(".hps",         new MimeType("application/vnd.hp-hps"));
        MIME_TYPES.put(".hdf",         new MimeType("application/x-hdf"));
        MIME_TYPES.put(".rip",         new MimeType("audio/vnd.rip"));
        MIME_TYPES.put(".hbci",        new MimeType("application/vnd.hbci"));
        MIME_TYPES.put(".jlt",         new MimeType("application/vnd.hp-jlyt"));
        MIME_TYPES.put(".pcl",         new MimeType("application/vnd.hp-pcl"));
        MIME_TYPES.put(".hpgl",        new MimeType("application/vnd.hp-hpgl"));
        MIME_TYPES.put(".hvs",         new MimeType("application/vnd.yamaha.hv-script"));
        MIME_TYPES.put(".hvd",         new MimeType("application/vnd.yamaha.hv-dic"));
        MIME_TYPES.put(".hvp",         new MimeType("application/vnd.yamaha.hv-voice"));
        MIME_TYPES.put(".sfd-hdstx",   new MimeType("application/vnd.hydrostatix.sof-data"));
        MIME_TYPES.put(".stk",         new MimeType("application/hyperstudio"));
        MIME_TYPES.put(".hal",         new MimeType("application/vnd.hal+xml"));
        MIME_TYPES.put(".html",        new MimeType("text/html"));
        MIME_TYPES.put(".irm",         new MimeType("application/vnd.ibm.rights-management"));
        MIME_TYPES.put(".sc",          new MimeType("application/vnd.ibm.secure-container"));
        MIME_TYPES.put(".ics",         new MimeType("text/calendar"));
        MIME_TYPES.put(".icc",         new MimeType("application/vnd.iccprofile"));
        MIME_TYPES.put(".ico",         new MimeType("image/x-icon"));
        MIME_TYPES.put(".igl",         new MimeType("application/vnd.igloader"));
        MIME_TYPES.put(".ief",         new MimeType("image/ief"));
        MIME_TYPES.put(".ivp",         new MimeType("application/vnd.immervision-ivp"));
        MIME_TYPES.put(".ivu",         new MimeType("application/vnd.immervision-ivu"));
        MIME_TYPES.put(".rif",         new MimeType("application/reginfo+xml"));
        MIME_TYPES.put(".3dml",        new MimeType("text/vnd.in3d.3dml"));
        MIME_TYPES.put(".spot",        new MimeType("text/vnd.in3d.spot"));
        MIME_TYPES.put(".igs",         new MimeType("model/iges"));
        MIME_TYPES.put(".i2g",         new MimeType("application/vnd.intergeo"));
        MIME_TYPES.put(".cdy",         new MimeType("application/vnd.cinderella"));
        MIME_TYPES.put(".xpw",         new MimeType("application/vnd.intercon.formnet"));
        MIME_TYPES.put(".fcs",         new MimeType("application/vnd.isac.fcs"));
        MIME_TYPES.put(".ipfix",       new MimeType("application/ipfix"));
        MIME_TYPES.put(".cer",         new MimeType("application/pkix-cert"));
        MIME_TYPES.put(".pki",         new MimeType("application/pkixcmp"));
        MIME_TYPES.put(".crl",         new MimeType("application/pkix-crl"));
        MIME_TYPES.put(".pkipath",     new MimeType("application/pkix-pkipath"));
        MIME_TYPES.put(".igm",         new MimeType("application/vnd.insors.igm"));
        MIME_TYPES.put(".rcprofile",   new MimeType("application/vnd.ipunplugged.rcprofile"));
        MIME_TYPES.put(".irp",         new MimeType("application/vnd.irepository.package+xml"));
        MIME_TYPES.put(".jad",         new MimeType("text/vnd.sun.j2me.app-descriptor"));
        MIME_TYPES.put(".jar",         new MimeType("application/java-archive"));
        MIME_TYPES.put(".class",       new MimeType("application/java-vm"));
        MIME_TYPES.put(".jnlp",        new MimeType("application/x-java-jnlp-file"));
        MIME_TYPES.put(".ser",         new MimeType("application/java-serialized-object"));
        MIME_TYPES.put(".java",        new MimeType("text/x-java-source,java"));
        MIME_TYPES.put(".js",          new MimeType("application/javascript"));
        MIME_TYPES.put(".json",        new MimeType("application/json"));
        MIME_TYPES.put(".joda",        new MimeType("application/vnd.joost.joda-archive"));
        MIME_TYPES.put(".jpm",         new MimeType("video/jpm"));
        MIME_TYPES.put(".jpeg",        new MimeType("image/jpeg"));
        MIME_TYPES.put(".jpg",         new MimeType("image/jpeg"));
        MIME_TYPES.put(".pjpeg",       new MimeType("image/pjpeg"));
        MIME_TYPES.put(".jpgv",        new MimeType("video/jpeg"));
        MIME_TYPES.put(".ktz",         new MimeType("application/vnd.kahootz"));
        MIME_TYPES.put(".mmd",         new MimeType("application/vnd.chipnuts.karaoke-mmd"));
        MIME_TYPES.put(".karbon",      new MimeType("application/vnd.kde.karbon"));
        MIME_TYPES.put(".chrt",        new MimeType("application/vnd.kde.kchart"));
        MIME_TYPES.put(".kfo",         new MimeType("application/vnd.kde.kformula"));
        MIME_TYPES.put(".flw",         new MimeType("application/vnd.kde.kivio"));
        MIME_TYPES.put(".kon",         new MimeType("application/vnd.kde.kontour"));
        MIME_TYPES.put(".kpr",         new MimeType("application/vnd.kde.kpresenter"));
        MIME_TYPES.put(".ksp",         new MimeType("application/vnd.kde.kspread"));
        MIME_TYPES.put(".kwd",         new MimeType("application/vnd.kde.kword"));
        MIME_TYPES.put(".htke",        new MimeType("application/vnd.kenameaapp"));
        MIME_TYPES.put(".kia",         new MimeType("application/vnd.kidspiration"));
        MIME_TYPES.put(".kne",         new MimeType("application/vnd.kinar"));
        MIME_TYPES.put(".sse",         new MimeType("application/vnd.kodak-descriptor"));
        MIME_TYPES.put(".lasxml",      new MimeType("application/vnd.las.las+xml"));
        MIME_TYPES.put(".latex",       new MimeType("application/x-latex"));
        MIME_TYPES.put(".lbd",         new MimeType("application/vnd.llamagraphics.life-balance.desktop"));
        MIME_TYPES.put(".lbe",         new MimeType("application/vnd.llamagraphics.life-balance.exchange+xml"));
        MIME_TYPES.put(".jam",         new MimeType("application/vnd.jam"));
        MIME_TYPES.put(".123",         new MimeType("application/vnd.lotus-1-2-3"));
        MIME_TYPES.put(".apr",         new MimeType("application/vnd.lotus-approach"));
        MIME_TYPES.put(".pre",         new MimeType("application/vnd.lotus-freelance"));
        MIME_TYPES.put(".nsf",         new MimeType("application/vnd.lotus-notes"));
        MIME_TYPES.put(".org",         new MimeType("application/vnd.lotus-organizer"));
        MIME_TYPES.put(".scm",         new MimeType("application/vnd.lotus-screencam"));
        MIME_TYPES.put(".lwp",         new MimeType("application/vnd.lotus-wordpro"));
        MIME_TYPES.put(".lvp",         new MimeType("audio/vnd.lucent.voice"));
        MIME_TYPES.put(".m3u",         new MimeType("audio/x-mpegurl"));
        MIME_TYPES.put(".m4v",         new MimeType("video/x-m4v"));
        MIME_TYPES.put(".hqx",         new MimeType("application/mac-binhex40"));
        MIME_TYPES.put(".portpkg",     new MimeType("application/vnd.macports.portpkg"));
        MIME_TYPES.put(".mgp",         new MimeType("application/vnd.osgeo.mapguide.package"));
        MIME_TYPES.put(".mrc",         new MimeType("application/marc"));
        MIME_TYPES.put(".mrcx",        new MimeType("application/marcxml+xml"));
        MIME_TYPES.put(".mxf",         new MimeType("application/mxf"));
        MIME_TYPES.put(".nbp",         new MimeType("application/vnd.wolfram.player"));
        MIME_TYPES.put(".ma",          new MimeType("application/mathematica"));
        MIME_TYPES.put(".mathml",      new MimeType("application/mathml+xml"));
        MIME_TYPES.put(".mbox",        new MimeType("application/mbox"));
        MIME_TYPES.put(".mc1",         new MimeType("application/vnd.medcalcdata"));
        MIME_TYPES.put(".mscml",       new MimeType("application/mediaservercontrol+xml"));
        MIME_TYPES.put(".cdkey",       new MimeType("application/vnd.mediastation.cdkey"));
        MIME_TYPES.put(".mwf",         new MimeType("application/vnd.mfer"));
        MIME_TYPES.put(".mfm",         new MimeType("application/vnd.mfmp"));
        MIME_TYPES.put(".msh",         new MimeType("model/mesh"));
        MIME_TYPES.put(".mads",        new MimeType("application/mads+xml"));
        MIME_TYPES.put(".mets",        new MimeType("application/mets+xml"));
        MIME_TYPES.put(".mods",        new MimeType("application/mods+xml"));
        MIME_TYPES.put(".meta4",       new MimeType("application/metalink4+xml"));
        MIME_TYPES.put(".mcd",         new MimeType("application/vnd.mcd"));
        MIME_TYPES.put(".flo",         new MimeType("application/vnd.micrografx.flo"));
        MIME_TYPES.put(".igx",         new MimeType("application/vnd.micrografx.igx"));
        MIME_TYPES.put(".es3",         new MimeType("application/vnd.eszigno3+xml"));
        MIME_TYPES.put(".mdb",         new MimeType("application/x-msaccess"));
        MIME_TYPES.put(".asf",         new MimeType("video/x-ms-asf"));
        MIME_TYPES.put(".exe",         new MimeType("application/x-msdownload"));
        MIME_TYPES.put(".cil",         new MimeType("application/vnd.ms-artgalry"));
        MIME_TYPES.put(".cab",         new MimeType("application/vnd.ms-cab-compressed"));
        MIME_TYPES.put(".ims",         new MimeType("application/vnd.ms-ims"));
        MIME_TYPES.put(".application", new MimeType("application/x-ms-application"));
        MIME_TYPES.put(".clp",         new MimeType("application/x-msclip"));
        MIME_TYPES.put(".mdi",         new MimeType("image/vnd.ms-modi"));
        MIME_TYPES.put(".eot",         new MimeType("application/vnd.ms-fontobject"));
        MIME_TYPES.put(".xls",         new MimeType("application/vnd.ms-excel"));
        MIME_TYPES.put(".xlam",        new MimeType("application/vnd.ms-excel.addin.macroenabled.12"));
        MIME_TYPES.put(".xlsb",        new MimeType("application/vnd.ms-excel.sheet.binary.macroenabled.12"));
        MIME_TYPES.put(".xltm",        new MimeType("application/vnd.ms-excel.template.macroenabled.12"));
        MIME_TYPES.put(".xlsm",        new MimeType("application/vnd.ms-excel.sheet.macroenabled.12"));
        MIME_TYPES.put(".chm",         new MimeType("application/vnd.ms-htmlhelp"));
        MIME_TYPES.put(".crd",         new MimeType("application/x-mscardfile"));
        MIME_TYPES.put(".lrm",         new MimeType("application/vnd.ms-lrm"));
        MIME_TYPES.put(".mvb",         new MimeType("application/x-msmediaview"));
        MIME_TYPES.put(".mny",         new MimeType("application/x-msmoney"));
        MIME_TYPES.put(".pptx",        new MimeType("application/vnd.openxmlformats-officedocument.presentationml.presentation"));
        MIME_TYPES.put(".sldx",        new MimeType("application/vnd.openxmlformats-officedocument.presentationml.slide"));
        MIME_TYPES.put(".ppsx",        new MimeType("application/vnd.openxmlformats-officedocument.presentationml.slideshow"));
        MIME_TYPES.put(".potx",        new MimeType("application/vnd.openxmlformats-officedocument.presentationml.template"));
        MIME_TYPES.put(".xlsx",        new MimeType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"));
        MIME_TYPES.put(".xltx",        new MimeType("application/vnd.openxmlformats-officedocument.spreadsheetml.template"));
        MIME_TYPES.put(".docx",        new MimeType("application/vnd.openxmlformats-officedocument.wordprocessingml.document"));
        MIME_TYPES.put(".dotx",        new MimeType("application/vnd.openxmlformats-officedocument.wordprocessingml.template"));
        MIME_TYPES.put(".obd",         new MimeType("application/x-msbinder"));
        MIME_TYPES.put(".thmx",        new MimeType("application/vnd.ms-officetheme"));
        MIME_TYPES.put(".onetoc",      new MimeType("application/onenote"));
        MIME_TYPES.put(".pya",         new MimeType("audio/vnd.ms-playready.media.pya"));
        MIME_TYPES.put(".pyv",         new MimeType("video/vnd.ms-playready.media.pyv"));
        MIME_TYPES.put(".ppt",         new MimeType("application/vnd.ms-powerpoint"));
        MIME_TYPES.put(".ppam",        new MimeType("application/vnd.ms-powerpoint.addin.macroenabled.12"));
        MIME_TYPES.put(".sldm",        new MimeType("application/vnd.ms-powerpoint.slide.macroenabled.12"));
        MIME_TYPES.put(".pptm",        new MimeType("application/vnd.ms-powerpoint.presentation.macroenabled.12"));
        MIME_TYPES.put(".ppsm",        new MimeType("application/vnd.ms-powerpoint.slideshow.macroenabled.12"));
        MIME_TYPES.put(".potm",        new MimeType("application/vnd.ms-powerpoint.template.macroenabled.12"));
        MIME_TYPES.put(".mpp",         new MimeType("application/vnd.ms-project"));
        MIME_TYPES.put(".pub",         new MimeType("application/x-mspublisher"));
        MIME_TYPES.put(".scd",         new MimeType("application/x-msschedule"));
        MIME_TYPES.put(".xap",         new MimeType("application/x-silverlight-app"));
        MIME_TYPES.put(".stl",         new MimeType("application/vnd.ms-pki.stl"));
        MIME_TYPES.put(".cat",         new MimeType("application/vnd.ms-pki.seccat"));
        MIME_TYPES.put(".vsd",         new MimeType("application/vnd.visio"));
        MIME_TYPES.put(".vsdx",        new MimeType("application/vnd.visio2013"));
        MIME_TYPES.put(".wm",          new MimeType("video/x-ms-wm"));
        MIME_TYPES.put(".wma",         new MimeType("audio/x-ms-wma"));
        MIME_TYPES.put(".wax",         new MimeType("audio/x-ms-wax"));
        MIME_TYPES.put(".wmx",         new MimeType("video/x-ms-wmx"));
        MIME_TYPES.put(".wmd",         new MimeType("application/x-ms-wmd"));
        MIME_TYPES.put(".wpl",         new MimeType("application/vnd.ms-wpl"));
        MIME_TYPES.put(".wmz",         new MimeType("application/x-ms-wmz"));
        MIME_TYPES.put(".wmv",         new MimeType("video/x-ms-wmv"));
        MIME_TYPES.put(".wvx",         new MimeType("video/x-ms-wvx"));
        MIME_TYPES.put(".wmf",         new MimeType("application/x-msmetafile"));
        MIME_TYPES.put(".trm",         new MimeType("application/x-msterminal"));
        MIME_TYPES.put(".doc",         new MimeType("application/msword"));
        MIME_TYPES.put(".docm",        new MimeType("application/vnd.ms-word.document.macroenabled.12"));
        MIME_TYPES.put(".dotm",        new MimeType("application/vnd.ms-word.template.macroenabled.12"));
        MIME_TYPES.put(".wri",         new MimeType("application/x-mswrite"));
        MIME_TYPES.put(".wps",         new MimeType("application/vnd.ms-works"));
        MIME_TYPES.put(".xbap",        new MimeType("application/x-ms-xbap"));
        MIME_TYPES.put(".xps",         new MimeType("application/vnd.ms-xpsdocument"));
        MIME_TYPES.put(".mid",         new MimeType("audio/midi"));
        MIME_TYPES.put(".mpy",         new MimeType("application/vnd.ibm.minipay"));
        MIME_TYPES.put(".afp",         new MimeType("application/vnd.ibm.modcap"));
        MIME_TYPES.put(".rms",         new MimeType("application/vnd.jcp.javame.midlet-rms"));
        MIME_TYPES.put(".tmo",         new MimeType("application/vnd.tmobile-livetv"));
        MIME_TYPES.put(".prc",         new MimeType("application/x-mobipocket-ebook"));
        MIME_TYPES.put(".mbk",         new MimeType("application/vnd.mobius.mbk"));
        MIME_TYPES.put(".dis",         new MimeType("application/vnd.mobius.dis"));
        MIME_TYPES.put(".plc",         new MimeType("application/vnd.mobius.plc"));
        MIME_TYPES.put(".mqy",         new MimeType("application/vnd.mobius.mqy"));
        MIME_TYPES.put(".msl",         new MimeType("application/vnd.mobius.msl"));
        MIME_TYPES.put(".txf",         new MimeType("application/vnd.mobius.txf"));
        MIME_TYPES.put(".daf",         new MimeType("application/vnd.mobius.daf"));
        MIME_TYPES.put(".fly",         new MimeType("text/vnd.fly"));
        MIME_TYPES.put(".mpc",         new MimeType("application/vnd.mophun.certificate"));
        MIME_TYPES.put(".mpn",         new MimeType("application/vnd.mophun.application"));
        MIME_TYPES.put(".mj2",         new MimeType("video/mj2"));
        MIME_TYPES.put(".mpga",        new MimeType("audio/mpeg"));
        MIME_TYPES.put(".mxu",         new MimeType("video/vnd.mpegurl"));
        MIME_TYPES.put(".mpeg",        new MimeType("video/mpeg"));
        MIME_TYPES.put(".m21",         new MimeType("application/mp21"));
        MIME_TYPES.put(".mp4a",        new MimeType("audio/mp4"));
        MIME_TYPES.put(".mp4",         new MimeType("video/mp4"));
        // MIME_TYPES.put(".mp4",      new MimeType("application/mp4"));
        MIME_TYPES.put(".m3u8",        new MimeType("application/vnd.apple.mpegurl"));
        MIME_TYPES.put(".mus",         new MimeType("application/vnd.musician"));
        MIME_TYPES.put(".msty",        new MimeType("application/vnd.muvee.style"));
        MIME_TYPES.put(".mxml",        new MimeType("application/xv+xml"));
        MIME_TYPES.put(".ngdat",       new MimeType("application/vnd.nokia.n-gage.data"));
        MIME_TYPES.put(".n-gage",      new MimeType("application/vnd.nokia.n-gage.symbian.install"));
        MIME_TYPES.put(".ncx",         new MimeType("application/x-dtbncx+xml"));
        MIME_TYPES.put(".nc",          new MimeType("application/x-netcdf"));
        MIME_TYPES.put(".nlu",         new MimeType("application/vnd.neurolanguage.nlu"));
        MIME_TYPES.put(".dna",         new MimeType("application/vnd.dna"));
        MIME_TYPES.put(".nnd",         new MimeType("application/vnd.noblenet-directory"));
        MIME_TYPES.put(".nns",         new MimeType("application/vnd.noblenet-sealer"));
        MIME_TYPES.put(".nnw",         new MimeType("application/vnd.noblenet-web"));
        MIME_TYPES.put(".rpst",        new MimeType("application/vnd.nokia.radio-preset"));
        MIME_TYPES.put(".rpss",        new MimeType("application/vnd.nokia.radio-presets"));
        MIME_TYPES.put(".n3",          new MimeType("text/n3"));
        MIME_TYPES.put(".edm",         new MimeType("application/vnd.novadigm.edm"));
        MIME_TYPES.put(".edx",         new MimeType("application/vnd.novadigm.edx"));
        MIME_TYPES.put(".ext",         new MimeType("application/vnd.novadigm.ext"));
        MIME_TYPES.put(".gph",         new MimeType("application/vnd.flographit"));
        MIME_TYPES.put(".ecelp4800",   new MimeType("audio/vnd.nuera.ecelp4800"));
        MIME_TYPES.put(".ecelp7470",   new MimeType("audio/vnd.nuera.ecelp7470"));
        MIME_TYPES.put(".ecelp9600",   new MimeType("audio/vnd.nuera.ecelp9600"));
        MIME_TYPES.put(".oda",         new MimeType("application/oda"));
        MIME_TYPES.put(".ogx",         new MimeType("application/ogg"));
        MIME_TYPES.put(".oga",         new MimeType("audio/ogg"));
        MIME_TYPES.put(".ogv",         new MimeType("video/ogg"));
        MIME_TYPES.put(".dd2",         new MimeType("application/vnd.oma.dd2+xml"));
        MIME_TYPES.put(".oth",         new MimeType("application/vnd.oasis.opendocument.text-web"));
        MIME_TYPES.put(".opf",         new MimeType("application/oebps-package+xml"));
        MIME_TYPES.put(".qbo",         new MimeType("application/vnd.intu.qbo"));
        MIME_TYPES.put(".oxt",         new MimeType("application/vnd.openofficeorg.extension"));
        MIME_TYPES.put(".osf",         new MimeType("application/vnd.yamaha.openscoreformat"));
        MIME_TYPES.put(".weba",        new MimeType("audio/webm"));
        MIME_TYPES.put(".webm",        new MimeType("video/webm"));
        MIME_TYPES.put(".odc",         new MimeType("application/vnd.oasis.opendocument.chart"));
        MIME_TYPES.put(".otc",         new MimeType("application/vnd.oasis.opendocument.chart-template"));
        MIME_TYPES.put(".odb",         new MimeType("application/vnd.oasis.opendocument.database"));
        MIME_TYPES.put(".odf",         new MimeType("application/vnd.oasis.opendocument.formula"));
        MIME_TYPES.put(".odft",        new MimeType("application/vnd.oasis.opendocument.formula-template"));
        MIME_TYPES.put(".odg",         new MimeType("application/vnd.oasis.opendocument.graphics"));
        MIME_TYPES.put(".otg",         new MimeType("application/vnd.oasis.opendocument.graphics-template"));
        MIME_TYPES.put(".odi",         new MimeType("application/vnd.oasis.opendocument.image"));
        MIME_TYPES.put(".oti",         new MimeType("application/vnd.oasis.opendocument.image-template"));
        MIME_TYPES.put(".odp",         new MimeType("application/vnd.oasis.opendocument.presentation"));
        MIME_TYPES.put(".otp",         new MimeType("application/vnd.oasis.opendocument.presentation-template"));
        MIME_TYPES.put(".ods",         new MimeType("application/vnd.oasis.opendocument.spreadsheet"));
        MIME_TYPES.put(".ots",         new MimeType("application/vnd.oasis.opendocument.spreadsheet-template"));
        MIME_TYPES.put(".odt",         new MimeType("application/vnd.oasis.opendocument.text"));
        MIME_TYPES.put(".odm",         new MimeType("application/vnd.oasis.opendocument.text-master"));
        MIME_TYPES.put(".ott",         new MimeType("application/vnd.oasis.opendocument.text-template"));
        MIME_TYPES.put(".ktx",         new MimeType("image/ktx"));
        MIME_TYPES.put(".sxc",         new MimeType("application/vnd.sun.xml.calc"));
        MIME_TYPES.put(".stc",         new MimeType("application/vnd.sun.xml.calc.template"));
        MIME_TYPES.put(".sxd",         new MimeType("application/vnd.sun.xml.draw"));
        MIME_TYPES.put(".std",         new MimeType("application/vnd.sun.xml.draw.template"));
        MIME_TYPES.put(".sxi",         new MimeType("application/vnd.sun.xml.impress"));
        MIME_TYPES.put(".sti",         new MimeType("application/vnd.sun.xml.impress.template"));
        MIME_TYPES.put(".sxm",         new MimeType("application/vnd.sun.xml.math"));
        MIME_TYPES.put(".sxw",         new MimeType("application/vnd.sun.xml.writer"));
        MIME_TYPES.put(".sxg",         new MimeType("application/vnd.sun.xml.writer.global"));
        MIME_TYPES.put(".stw",         new MimeType("application/vnd.sun.xml.writer.template"));
        MIME_TYPES.put(".otf",         new MimeType("application/x-font-otf"));
        MIME_TYPES.put(".osfpvg",      new MimeType("application/vnd.yamaha.openscoreformat.osfpvg+xml"));
        MIME_TYPES.put(".dp",          new MimeType("application/vnd.osgi.dp"));
        MIME_TYPES.put(".pdb",         new MimeType("application/vnd.palm"));
        MIME_TYPES.put(".p",           new MimeType("text/x-pascal"));
        MIME_TYPES.put(".paw",         new MimeType("application/vnd.pawaafile"));
        MIME_TYPES.put(".pclxl",       new MimeType("application/vnd.hp-pclxl"));
        MIME_TYPES.put(".efif",        new MimeType("application/vnd.picsel"));
        MIME_TYPES.put(".pcx",         new MimeType("image/x-pcx"));
        MIME_TYPES.put(".psd",         new MimeType("image/vnd.adobe.photoshop"));
        MIME_TYPES.put(".prf",         new MimeType("application/pics-rules"));
        MIME_TYPES.put(".pic",         new MimeType("image/x-pict"));
        MIME_TYPES.put(".chat",        new MimeType("application/x-chat"));
        MIME_TYPES.put(".p10",         new MimeType("application/pkcs10"));
        MIME_TYPES.put(".p12",         new MimeType("application/x-pkcs12"));
        MIME_TYPES.put(".p7m",         new MimeType("application/pkcs7-mime"));
        MIME_TYPES.put(".p7s",         new MimeType("application/pkcs7-signature"));
        MIME_TYPES.put(".p7r",         new MimeType("application/x-pkcs7-certreqresp"));
        MIME_TYPES.put(".p7b",         new MimeType("application/x-pkcs7-certificates"));
        MIME_TYPES.put(".p8",          new MimeType("application/pkcs8"));
        MIME_TYPES.put(".plf",         new MimeType("application/vnd.pocketlearn"));
        MIME_TYPES.put(".pnm",         new MimeType("image/x-portable-anymap"));
        MIME_TYPES.put(".pbm",         new MimeType("image/x-portable-bitmap"));
        MIME_TYPES.put(".pcf",         new MimeType("application/x-font-pcf"));
        MIME_TYPES.put(".pfr",         new MimeType("application/font-tdpfr"));
        MIME_TYPES.put(".pgn",         new MimeType("application/x-chess-pgn"));
        MIME_TYPES.put(".pgm",         new MimeType("image/x-portable-graymap"));
        MIME_TYPES.put(".png",         new MimeType("image/png"));
        // MIME_TYPES.put(".png",      new MimeType("image/x-citrix-png"));
        // MIME_TYPES.put(".png",      new MimeType("image/x-png"));
        MIME_TYPES.put(".ppm",         new MimeType("image/x-portable-pixmap"));
        MIME_TYPES.put(".pskcxml",     new MimeType("application/pskc+xml"));
        MIME_TYPES.put(".pml",         new MimeType("application/vnd.ctc-posml"));
        MIME_TYPES.put(".ai",          new MimeType("application/postscript"));
        MIME_TYPES.put(".pfa",         new MimeType("application/x-font-type1"));
        MIME_TYPES.put(".pbd",         new MimeType("application/vnd.powerbuilder6"));
        MIME_TYPES.put(".pgp",         new MimeType("application/pgp-encrypted"));
        // MIME_TYPES.put(".pgp",      new MimeType("application/pgp-signature"));
        MIME_TYPES.put(".box",         new MimeType("application/vnd.previewsystems.box"));
        MIME_TYPES.put(".ptid",        new MimeType("application/vnd.pvi.ptid1"));
        MIME_TYPES.put(".pls",         new MimeType("application/pls+xml"));
        MIME_TYPES.put(".str",         new MimeType("application/vnd.pg.format"));
        MIME_TYPES.put(".ei6",         new MimeType("application/vnd.pg.osasli"));
        MIME_TYPES.put(".dsc",         new MimeType("text/prs.lines.tag"));
        MIME_TYPES.put(".psf",         new MimeType("application/x-font-linux-psf"));
        MIME_TYPES.put(".qps",         new MimeType("application/vnd.publishare-delta-tree"));
        MIME_TYPES.put(".wg",          new MimeType("application/vnd.pmi.widget"));
        MIME_TYPES.put(".qxd",         new MimeType("application/vnd.quark.quarkxpress"));
        MIME_TYPES.put(".esf",         new MimeType("application/vnd.epson.esf"));
        MIME_TYPES.put(".msf",         new MimeType("application/vnd.epson.msf"));
        MIME_TYPES.put(".ssf",         new MimeType("application/vnd.epson.ssf"));
        MIME_TYPES.put(".qam",         new MimeType("application/vnd.epson.quickanime"));
        MIME_TYPES.put(".qfx",         new MimeType("application/vnd.intu.qfx"));
        MIME_TYPES.put(".qt",          new MimeType("video/quicktime"));
        MIME_TYPES.put(".rar",         new MimeType("application/x-rar-compressed"));
        MIME_TYPES.put(".ram",         new MimeType("audio/x-pn-realaudio"));
        MIME_TYPES.put(".rmp",         new MimeType("audio/x-pn-realaudio-plugin"));
        MIME_TYPES.put(".rsd",         new MimeType("application/rsd+xml"));
        MIME_TYPES.put(".rm",          new MimeType("application/vnd.rn-realmedia"));
        MIME_TYPES.put(".bed",         new MimeType("application/vnd.realvnc.bed"));
        MIME_TYPES.put(".mxl",         new MimeType("application/vnd.recordare.musicxml"));
        MIME_TYPES.put(".musicxml",    new MimeType("application/vnd.recordare.musicxml+xml"));
        MIME_TYPES.put(".rnc",         new MimeType("application/relax-ng-compact-syntax"));
        MIME_TYPES.put(".rdz",         new MimeType("application/vnd.data-vision.rdz"));
        MIME_TYPES.put(".rdf",         new MimeType("application/rdf+xml"));
        MIME_TYPES.put(".rp9",         new MimeType("application/vnd.cloanto.rp9"));
        MIME_TYPES.put(".jisp",        new MimeType("application/vnd.jisp"));
        MIME_TYPES.put(".rtf",         new MimeType("application/rtf"));
        MIME_TYPES.put(".rtx",         new MimeType("text/richtext"));
        MIME_TYPES.put(".link66",      new MimeType("application/vnd.route66.link66+xml"));
        MIME_TYPES.put(".rss, .xml",   new MimeType("application/rss+xml"));
        MIME_TYPES.put(".shf",         new MimeType("application/shf+xml"));
        MIME_TYPES.put(".st",          new MimeType("application/vnd.sailingtracker.track"));
        MIME_TYPES.put(".svg",         new MimeType("image/svg+xml"));
        MIME_TYPES.put(".sus",         new MimeType("application/vnd.sus-calendar"));
        MIME_TYPES.put(".sru",         new MimeType("application/sru+xml"));
        MIME_TYPES.put(".setpay",      new MimeType("application/set-payment-initiation"));
        MIME_TYPES.put(".setreg",      new MimeType("application/set-registration-initiation"));
        MIME_TYPES.put(".sema",        new MimeType("application/vnd.sema"));
        MIME_TYPES.put(".semd",        new MimeType("application/vnd.semd"));
        MIME_TYPES.put(".semf",        new MimeType("application/vnd.semf"));
        MIME_TYPES.put(".see",         new MimeType("application/vnd.seemail"));
        MIME_TYPES.put(".snf",         new MimeType("application/x-font-snf"));
        MIME_TYPES.put(".spq",         new MimeType("application/scvp-vp-request"));
        MIME_TYPES.put(".spp",         new MimeType("application/scvp-vp-response"));
        MIME_TYPES.put(".scq",         new MimeType("application/scvp-cv-request"));
        MIME_TYPES.put(".scs",         new MimeType("application/scvp-cv-response"));
        MIME_TYPES.put(".sdp",         new MimeType("application/sdp"));
        MIME_TYPES.put(".etx",         new MimeType("text/x-setext"));
        MIME_TYPES.put(".movie",       new MimeType("video/x-sgi-movie"));
        MIME_TYPES.put(".ifm",         new MimeType("application/vnd.shana.informed.formdata"));
        MIME_TYPES.put(".itp",         new MimeType("application/vnd.shana.informed.formtemplate"));
        MIME_TYPES.put(".iif",         new MimeType("application/vnd.shana.informed.interchange"));
        MIME_TYPES.put(".ipk",         new MimeType("application/vnd.shana.informed.package"));
        MIME_TYPES.put(".tfi",         new MimeType("application/thraud+xml"));
        MIME_TYPES.put(".shar",        new MimeType("application/x-shar"));
        MIME_TYPES.put(".rgb",         new MimeType("image/x-rgb"));
        MIME_TYPES.put(".slt",         new MimeType("application/vnd.epson.salt"));
        MIME_TYPES.put(".aso",         new MimeType("application/vnd.accpac.simply.aso"));
        MIME_TYPES.put(".imp",         new MimeType("application/vnd.accpac.simply.imp"));
        MIME_TYPES.put(".twd",         new MimeType("application/vnd.simtech-mindmapper"));
        MIME_TYPES.put(".csp",         new MimeType("application/vnd.commonspace"));
        MIME_TYPES.put(".saf",         new MimeType("application/vnd.yamaha.smaf-audio"));
        MIME_TYPES.put(".mmf",         new MimeType("application/vnd.smaf"));
        MIME_TYPES.put(".spf",         new MimeType("application/vnd.yamaha.smaf-phrase"));
        MIME_TYPES.put(".teacher",     new MimeType("application/vnd.smart.teacher"));
        MIME_TYPES.put(".svd",         new MimeType("application/vnd.svd"));
        MIME_TYPES.put(".rq",          new MimeType("application/sparql-query"));
        MIME_TYPES.put(".srx",         new MimeType("application/sparql-results+xml"));
        MIME_TYPES.put(".gram",        new MimeType("application/srgs"));
        MIME_TYPES.put(".grxml",       new MimeType("application/srgs+xml"));
        MIME_TYPES.put(".ssml",        new MimeType("application/ssml+xml"));
        MIME_TYPES.put(".skp",         new MimeType("application/vnd.koan"));
        MIME_TYPES.put(".sgml",        new MimeType("text/sgml"));
        MIME_TYPES.put(".sdc",         new MimeType("application/vnd.stardivision.calc"));
        MIME_TYPES.put(".sda",         new MimeType("application/vnd.stardivision.draw"));
        MIME_TYPES.put(".sdd",         new MimeType("application/vnd.stardivision.impress"));
        MIME_TYPES.put(".smf",         new MimeType("application/vnd.stardivision.math"));
        MIME_TYPES.put(".sdw",         new MimeType("application/vnd.stardivision.writer"));
        MIME_TYPES.put(".sgl",         new MimeType("application/vnd.stardivision.writer-global"));
        MIME_TYPES.put(".sm",          new MimeType("application/vnd.stepmania.stepchart"));
        MIME_TYPES.put(".sit",         new MimeType("application/x-stuffit"));
        MIME_TYPES.put(".sitx",        new MimeType("application/x-stuffitx"));
        MIME_TYPES.put(".sdkm",        new MimeType("application/vnd.solent.sdkm+xml"));
        MIME_TYPES.put(".xo",          new MimeType("application/vnd.olpc-sugar"));
        MIME_TYPES.put(".au",          new MimeType("audio/basic"));
        MIME_TYPES.put(".wqd",         new MimeType("application/vnd.wqd"));
        MIME_TYPES.put(".sis",         new MimeType("application/vnd.symbian.install"));
        MIME_TYPES.put(".smi",         new MimeType("application/smil+xml"));
        MIME_TYPES.put(".xsm",         new MimeType("application/vnd.syncml+xml"));
        MIME_TYPES.put(".bdm",         new MimeType("application/vnd.syncml.dm+wbxml"));
        MIME_TYPES.put(".xdm",         new MimeType("application/vnd.syncml.dm+xml"));
        MIME_TYPES.put(".sv4cpio",     new MimeType("application/x-sv4cpio"));
        MIME_TYPES.put(".sv4crc",      new MimeType("application/x-sv4crc"));
        MIME_TYPES.put(".sbml",        new MimeType("application/sbml+xml"));
        MIME_TYPES.put(".tsv",         new MimeType("text/tab-separated-values"));
        MIME_TYPES.put(".tiff",        new MimeType("image/tiff"));
        MIME_TYPES.put(".tao",         new MimeType("application/vnd.tao.intent-module-archive"));
        MIME_TYPES.put(".tar",         new MimeType("application/x-tar"));
        MIME_TYPES.put(".tcl",         new MimeType("application/x-tcl"));
        MIME_TYPES.put(".tex",         new MimeType("application/x-tex"));
        MIME_TYPES.put(".tfm",         new MimeType("application/x-tex-tfm"));
        MIME_TYPES.put(".tei",         new MimeType("application/tei+xml"));
        MIME_TYPES.put(".txt",         new MimeType("text/plain"));
        MIME_TYPES.put(".dxp",         new MimeType("application/vnd.spotfire.dxp"));
        MIME_TYPES.put(".sfs",         new MimeType("application/vnd.spotfire.sfs"));
        MIME_TYPES.put(".tsd",         new MimeType("application/timestamped-data"));
        MIME_TYPES.put(".tpt",         new MimeType("application/vnd.trid.tpt"));
        MIME_TYPES.put(".mxs",         new MimeType("application/vnd.triscape.mxs"));
        MIME_TYPES.put(".t",           new MimeType("text/troff"));
        MIME_TYPES.put(".tra",         new MimeType("application/vnd.trueapp"));
        MIME_TYPES.put(".ttf",         new MimeType("application/x-font-ttf"));
        MIME_TYPES.put(".ttl",         new MimeType("text/turtle"));
        MIME_TYPES.put(".umj",         new MimeType("application/vnd.umajin"));
        MIME_TYPES.put(".uoml",        new MimeType("application/vnd.uoml+xml"));
        MIME_TYPES.put(".unityweb",    new MimeType("application/vnd.unity"));
        MIME_TYPES.put(".ufd",         new MimeType("application/vnd.ufdl"));
        MIME_TYPES.put(".uri",         new MimeType("text/uri-list"));
        MIME_TYPES.put(".utz",         new MimeType("application/vnd.uiq.theme"));
        MIME_TYPES.put(".ustar",       new MimeType("application/x-ustar"));
        MIME_TYPES.put(".uu",          new MimeType("text/x-uuencode"));
        MIME_TYPES.put(".vcs",         new MimeType("text/x-vcalendar"));
        MIME_TYPES.put(".vcf",         new MimeType("text/x-vcard"));
        MIME_TYPES.put(".vcd",         new MimeType("application/x-cdlink"));
        MIME_TYPES.put(".vsf",         new MimeType("application/vnd.vsf"));
        MIME_TYPES.put(".wrl",         new MimeType("model/vrml"));
        MIME_TYPES.put(".vcx",         new MimeType("application/vnd.vcx"));
        MIME_TYPES.put(".mts",         new MimeType("model/vnd.mts"));
        MIME_TYPES.put(".vtu",         new MimeType("model/vnd.vtu"));
        MIME_TYPES.put(".vis",         new MimeType("application/vnd.visionary"));
        MIME_TYPES.put(".viv",         new MimeType("video/vnd.vivo"));
        MIME_TYPES.put(".ccxml",       new MimeType("application/ccxml+xml,"));
        MIME_TYPES.put(".vxml",        new MimeType("application/voicexml+xml"));
        MIME_TYPES.put(".src",         new MimeType("application/x-wais-source"));
        MIME_TYPES.put(".wbxml",       new MimeType("application/vnd.wap.wbxml"));
        MIME_TYPES.put(".wbmp",        new MimeType("image/vnd.wap.wbmp"));
        MIME_TYPES.put(".wav",         new MimeType("audio/x-wav"));
        MIME_TYPES.put(".davmount",    new MimeType("application/davmount+xml"));
        MIME_TYPES.put(".woff",        new MimeType("application/x-font-woff"));
        MIME_TYPES.put(".wspolicy",    new MimeType("application/wspolicy+xml"));
        MIME_TYPES.put(".webp",        new MimeType("image/webp"));
        MIME_TYPES.put(".wtb",         new MimeType("application/vnd.webturbo"));
        MIME_TYPES.put(".wgt",         new MimeType("application/widget"));
        MIME_TYPES.put(".hlp",         new MimeType("application/winhlp"));
        MIME_TYPES.put(".wml",         new MimeType("text/vnd.wap.wml"));
        MIME_TYPES.put(".wmls",        new MimeType("text/vnd.wap.wmlscript"));
        MIME_TYPES.put(".wmlsc",       new MimeType("application/vnd.wap.wmlscriptc"));
        MIME_TYPES.put(".wpd",         new MimeType("application/vnd.wordperfect"));
        MIME_TYPES.put(".stf",         new MimeType("application/vnd.wt.stf"));
        MIME_TYPES.put(".wsdl",        new MimeType("application/wsdl+xml"));
        MIME_TYPES.put(".xbm",         new MimeType("image/x-xbitmap"));
        MIME_TYPES.put(".xpm",         new MimeType("image/x-xpixmap"));
        MIME_TYPES.put(".xwd",         new MimeType("image/x-xwindowdump"));
        MIME_TYPES.put(".der",         new MimeType("application/x-x509-ca-cert"));
        MIME_TYPES.put(".fig",         new MimeType("application/x-xfig"));
        MIME_TYPES.put(".xhtml",       new MimeType("application/xhtml+xml"));
        MIME_TYPES.put(".xml",         new MimeType("application/xml"));
        MIME_TYPES.put(".xdf",         new MimeType("application/xcap-diff+xml"));
        MIME_TYPES.put(".xenc",        new MimeType("application/xenc+xml"));
        MIME_TYPES.put(".xer",         new MimeType("application/patch-ops-error+xml"));
        MIME_TYPES.put(".rl",          new MimeType("application/resource-lists+xml"));
        MIME_TYPES.put(".rs",          new MimeType("application/rls-services+xml"));
        MIME_TYPES.put(".rld",         new MimeType("application/resource-lists-diff+xml"));
        MIME_TYPES.put(".xslt",        new MimeType("application/xslt+xml"));
        MIME_TYPES.put(".xop",         new MimeType("application/xop+xml"));
        MIME_TYPES.put(".xpi",         new MimeType("application/x-xpinstall"));
        MIME_TYPES.put(".xspf",        new MimeType("application/xspf+xml"));
        MIME_TYPES.put(".xul",         new MimeType("application/vnd.mozilla.xul+xml"));
        MIME_TYPES.put(".xyz",         new MimeType("chemical/x-xyz"));
        MIME_TYPES.put(".yaml",        new MimeType("text/yaml"));
        MIME_TYPES.put(".yang",        new MimeType("application/yang"));
        MIME_TYPES.put(".yin",         new MimeType("application/yin+xml"));
        MIME_TYPES.put(".zir",         new MimeType("application/vnd.zul"));
        MIME_TYPES.put(".zip",         new MimeType("application/zip"));
        MIME_TYPES.put(".zmm",         new MimeType("application/vnd.handheld-entertainment+xml"));
        MIME_TYPES.put(".zaz",         new MimeType("application/vnd.zzazz.deck+xml"));
        // @formatter:on
    }

    private final String type;

    private MimeType(final String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return type;
    }

    /**
     * Get the type string, e.g. for a <code>.html</code> file it would be <code>text/html</code>
     *
     * @return The type string
     */
    public String getType() {
        return type;
    }

    /**
     * Get the mime type that should be used for the defined file
     *
     * @param file The file to get the mime type for
     * @return The mime type of this file
     */
    public static MimeType getMimeType(final File file) {
        final String extension = file.getName().substring(file.getName().lastIndexOf('.'));

        return MIME_TYPES.getOrDefault(extension, new MimeType("application/octet-stream"));
    }

}
